# Generated by Django 5.1.7 on 2025-08-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('preferred_date', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_processing_consent', models.BooleanField(default=False)),
                ('data_processing_consent_date', models.DateTimeField(auto_now_add=True)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('marketing_consent_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
            },
        ),
    ]
