# Generated by Django 5.1.7 on 2025-08-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSubjectRightsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('access', 'Żądanie dostępu do danych'), ('rectification', 'Żądanie sprostowania danych'), ('erasure', 'Żądanie usunięcia danych'), ('portability', 'Żądanie przenoszenia danych'), ('restriction', 'Żądanie ograniczenia przetwarzania'), ('objection', 'Sprzeciw wobec przetwarzania')], max_length=20)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('identification', models.TextField()),
                ('details', models.TextField(blank=True, null=True)),
                ('privacy_consent', models.BooleanField(default=False)),
                ('privacy_consent_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('in_progress', 'W trakcie realizacji'), ('completed', 'Zakończone'), ('rejected', 'Odrzucone')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_number', models.CharField(blank=True, max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Data Subject Rights Request',
                'verbose_name_plural': 'Data Subject Rights Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
