# Generated by Django 5.1.7 on 2025-08-27 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_datasubjectrightsrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tytuł artykułu (ważny dla SEO)', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL artykułu (automatycznie generowany)', max_length=200, unique=True)),
                ('meta_description', models.CharField(blank=True, help_text='Opis dla wyszukiwarek (max 160 znaków)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Słowa kluczowe oddzielone przecinkami', max_length=255)),
                ('excerpt', models.TextField(help_text='Krótki opis artykułu (wyświetlany na liście)', max_length=300)),
                ('content', models.TextField(help_text='Treść artykułu (obsługuje HTML)')),
                ('featured_image', models.CharField(blank=True, help_text='URL do głównego zdjęcia artykułu', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('published', 'Opublikowane')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_time', models.PositiveIntegerField(default=5, help_text='Szacowany czas czytania w minutach')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
