# Generated by Django 5.1.7 on 2025-09-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blogcategory_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title', models.CharField(help_text='np. Psycholog, Terapeuta', max_length=200)),
                ('specialization', models.CharField(help_text='np. Terapia poznawczo-behawioralna, Terapia par', max_length=300)),
                ('bio', models.TextField(help_text='Krótki opis osoby i doświadczenia')),
                ('education', models.TextField(blank=True, help_text='Wykształcenie i kwalifikacje')),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Lata doświadczenia')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('photo', models.CharField(blank=True, help_text='URL do zdjęcia pracownika', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Kolejność wyświetlania na stronie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['display_order', 'last_name'],
            },
        ),
    ]
