# Generated by Django 5.1.7 on 2025-11-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_staffmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics_consent', models.BooleanField(default=False, help_text='Whether user consented to analytics cookies')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user (for audit purposes)', null=True)),
                ('session_key', models.CharField(blank=True, help_text='Session identifier to track consent changes', max_length=40)),
                ('user_agent', models.CharField(blank=True, help_text='Browser user agent string', max_length=500)),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cookie Consent',
                'verbose_name_plural': 'Cookie Consents',
                'ordering': ['-consented_at'],
            },
        ),
    ]
