# Generated by Django 5.1.7 on 2026-03-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cookieconsent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('company', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(choices=[('antymobbingowe_pracownicy', 'Szkolenie antymobbingowe dla pracowników'), ('antymobbingowe_kadra', 'Szkolenie dla kadry zarządzającej i HR'), ('procedura', 'Wdrożenie procedury antymobbingowej'), ('pakiet', 'Pakiet PEŁNY'), ('inne', 'Inne / Konsultacja')], default='inne', max_length=50)),
                ('message', models.TextField(blank=True)),
                ('data_processing_consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Training Inquiry',
                'verbose_name_plural': 'Training Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
