# Generated by Django 5.2.5 on 2026-08-24 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_traininginquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffMember',
        ),
    ]
